---
- name: Add Key for Nginx Mainline Repository
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: Add Nginx Mainline Repository
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx' state=present

- name: Install Nginx
  apt: pkg=nginx state=present

- name: Set htpasswd users
  htpasswd: path=/etc/nginx/htpasswd name="{{ nginx.basicauth.user }}" password="{{ nginx.basicauth.password }}"
  when: nginx.basicauth.enabled | default(false)

- name: Create SSL directory
  file: dest=/etc/nginx/ssl state=directory
  when: nginx.ssl | default(false)

- name: Generate strong unique Diffie-Hellman group.
  command: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/nginx/ssl/
    creates: /etc/nginx/ssl/dhparams.pem
  when: nginx.ssl | default(false)

- name: Generate self-signed SSL certificate
  shell: >
    openssl req -subj "/CN={{ nginx.hostname }}" -new
    -newkey rsa:2048 -days 3650 -nodes -x509 -sha256
    -keyout {{ nginx.hostname }}_self_signed.key -out {{ nginx.hostname }}_self_signed.pem
  args:
    chdir: /etc/nginx/ssl/
  when: nginx.ssl | default(false)

- name: Copy ssl configuration
  copy: src=ssl.conf dest=/etc/nginx/ssl.conf
  when: nginx.ssl | default(false)

- name: Copy ssl-stapling configuration
  copy: src=ssl-stapling.conf dest=/etc/nginx/ssl-stapling.conf
  when: nginx.ssl | default(false)

- name: Set default Nginx user to www-data
  lineinfile: "dest=/etc/nginx/nginx.conf state=present regexp='^user (.*);' line='user {{ httpd_user }};'"

- name: Change default Nginx site
  template: src=default.tpl dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
