---
- name: Add Key for Nginx Mainline Repository
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: Add Nginx Mainline Repository
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx' state=present

- name: Install Nginx
  apt: pkg=nginx state=present

- name: Set default Nginx user to www-data
  lineinfile: "dest=/etc/nginx/nginx.conf state=present regexp='^user (.*);' line='user {{ server.http_user }};'"

- name: Change default Nginx site
  template: src=default.tpl dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
