---
- hosts: all
  become: true
  roles:
    - role: ntp
      tags: ntp
    - role: erlang
      tags: erlang
    - role: elixir
      tags: elixir
    - role: phoenix
      tags: phoenix
    - role: postgresql
      tags: postgresql
    - role: nginx
      tags: nginx
    - role: vagrant
      tags: vagrant
